# ?????
spring.datasource.url=jdbc:mysql://localhost:3306/worddb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=150604
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ?????
server.port=8080

# file.md???????????classpath??????????JVM??-Dapp.file-md-path???
app.file-md-path=
